#
# bashrc
#
# Configurations for bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source all the aliases
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc" ] && \
    source "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc"

# Source file for adding git to shell prompt
. ~/.config/git/git-prompt.sh

# History settings
HISTFILE="${XDG_CONFIG_HOME:-$HOME/.config}/bash/bash_history"
HISTSIZE=1000
HISTFILESIZE=2000
HISTCONTROL=ignoreboth
shopt -s histappend

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

# Set user prompt
if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=yes
    fi
fi

if [ "$color_prompt" = yes ]; then
    PROMPT_BEFORE="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;36m\]"
else
    PROMPT_BEFORE="${debian_chroot:+($debian_chroot)}\u@\h:\w"
fi
unset color_prompt force_color_prompt

# Set user prompt with git
PROMPT_AFTER="\n\[\033[0m\]\$ "
PROMPT_COMMAND='__git_ps1 "$PROMPT_BEFORE" "$PROMPT_AFTER"'

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Enable git completion
eval "$(gh completion -s bash)"

# Enable tab completion when using sudo
[ "$PS1" ] && complete -cf sudo
